services:
  backend:
    environment:
      CHATBOT_SSO_SECRET: ${CHATBOT_SSO_SECRET:?Start using gateway start.ps1 to initialize SSO}
  frontend:
    build:
      args:
        NEXT_PUBLIC_BASE_PATH: /chatbot
    environment:
      NEXT_PUBLIC_BASE_PATH: /chatbot
    ports: !override
      - "127.0.0.1:3000:3000"
    networks:
      default: {}
      shared:
        aliases: [chatbot-web]

networks:
  shared:
    external: true
    name: oplai_gateway
